### ISSUE TITLE
Request for adding PNG tiles covering galactic center

### ISSUE THREAD

**Issue by adl1995** [hipspy/hips-extra#5]
Currently the test case for `SimpleTilePainter` is missing PNG tiles. It would be great if @tboch or @cdeil  could add them.

**Comment by cdeil** [comment]
I see that currently we have these PNG tiles in `hips-extra`:
```
        ├── 2MASS6XH
        │   ├── Norder6
        │   │   └── Dir0
        │   │       ├── Npix1517.png
        │   │       ├── Npix6077.png
        │   │       ├── Npix6112.png
        │   │       ├── Npix6114.png
        │   │       └── Npix6120.png
        │   └── properties
        ├── AKARI-FIS
        │   ├── Norder3
        │   │   └── Dir0
        │   │       ├── Npix450.png
        │   │       ├── Npix451.png
        │   │       ├── Npix452.png
        │   │       ├── Npix453.png
        │   │       ├── Npix454.png
        │   │       ├── Npix455.png
        │   │       └── Npix456.png
```
@adl1995 - Do these work? Or which others do you need?

**Comment by cdeil** [comment]
As far as I can see you always fetch tiles anyways at the moment for all `SimpleTilePainter` tests:
https://github.com/hipspy/hips/pull/66/files#r127173397

So you can just use `AKARI-FIS` for PNG and fetch them from CDS, no?

@tboch  -- is there a problem either with this survey HiPS data or Aladin lite?
http://alasky.u-strasbg.fr/AKARI-FIS/N160/
I see all white and in the Chrome dev console see:
```
(index):14 Uncaught TypeError: Cannot set property 'innerHTML' of null
    at (index):14
GET http://alasky.u-strasbg.fr/AKARI-FIS/N160/Norder3/Allsky.jpg 404 (Not Found)
```

**Comment by cdeil** [comment]
Ah, when I go to full-screen, I do see an image (and not all white):

@tboch - I guess the background text shouldn't be visible in fullscreen mode?

![screen shot 2017-07-13 at 11 51 46](https://user-images.githubusercontent.com/852409/28160847-b58ae7f2-67c1-11e7-9c9c-821d0ac1baf9.png)

@adl1995 - I think for now, to finish up https://github.com/hipspy/hips/pull/66 , you can use http://alasky.u-strasbg.fr/AKARI-FIS/N160/ for the tests, no?

**Comment by tboch** [comment]
> Ah, when I go to full-screen, I do see an image (and not all white):
> 
> @tboch - I guess the background text shouldn't be visible in fullscreen mode?

yes, that's a known bug. Sorry about that.

> @tboch -- is there a problem either with this survey HiPS data or Aladin lite?
> http://alasky.u-strasbg.fr/AKARI-FIS/N160/

the Allsky.png file seems to be all black, I'll investigate.
Thanks for catching this.

**Comment by cdeil** [comment]
I think the original issue is resolved, or at least it's not clear to me what needs to be done.
Closing now.

@tboch - You might want to have a look at your last comment and see if that issue with http://alasky.u-strasbg.fr/AKARI-FIS/N160/ or Aladin lite is resolved by now.
